ed build-all: shellcheck fixes

diff --git a/build-all b/build-all
--- a/build-all
+++ b/build-all
@@ -7,22 +7,19 @@ readonly here="$(dirname "${this}")"
 readonly whatami="$(basename "${this}")"
 readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
 
-readonly default_distribution="xenial"
-readonly default_ros_distro="kinetic"
-
-log() { echo "${whatami}[$$]: $@" >&2; }
-error() { log "ERROR: $@"; }
-warning() { log "WARNING: $@"; }
-info() { log "INFO: $@"; }
+log() { echo "${whatami}[$$]: $*" >&2; }
+error() { log "ERROR: $*"; }
+warning() { log "WARNING: $*"; }
+info() { log "INFO: $*"; }
 
 die() {
-    error "$@"
+    error "$*"
     usage >&2
     exit 1
 }
 
 cleanup() {
-    local status="$?"
+    status="$?"
     rm -rf "${tmpdir}"
     if command -v docker >/dev/null 2>&1; then
         docker system prune --force --filter until=6h >&2 || true
@@ -48,7 +45,7 @@ git -C "${here}" branch -a \
     | sed -nr 's|^  remotes/[^/]+/([[:graph:]]+)$|\1|gp' \
     | sed 's/master/latest/' \
     | sort -u \
-    | while read brunch; do
+    | while read -r brunch; do
     export IMAGE_NAME="registry.gitlab.com/realtime-robotics/ros-dpkg:${brunch}"
     "${here}/hooks/build"
 done
